# Generated by Django 4.1.7 on 2023-03-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=80)),
                ('education_level', models.CharField(choices=[('primary', 'Primary'), ('gymnasium', 'Gymnasium'), ('highschool', 'Highschool')], max_length=50)),
                ('course', models.CharField(choices=[('literature', 'Literature'), ('math', 'Math'), ('history', 'history'), ('biology', 'Biology'), ('physiscs', 'Physics'), ('english', 'English'), ('geography', 'Geography')], max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
