# Generated by Django 4.1.7 on 2023-03-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(default=125485632, max_length=14),
            preserve_default=False,
        ),
    ]
