# Generated by Django 4.1.7 on 2023-05-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_alter_teacher_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homework_title', models.CharField(max_length=150)),
                ('homework_description', models.TextField(max_length=2000)),
                ('due_date', models.DateField()),
                ('discipline', models.CharField(choices=[('literature', 'Literature'), ('math', 'Math'), ('history', 'history'), ('biology', 'Biology'), ('physiscs', 'Physics'), ('english', 'English'), ('geography', 'Geography')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('file', models.FileField(blank=True, null=True, upload_to='file/')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
