# Generated by Django 4.1.7 on 2023-05-06 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('headmaster', '0002_alter_classroom_class_master'),
        ('teacher', '0005_homework'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='headmaster.classroom'),
        ),
    ]
