# Generated by Django 4.1.7 on 2023-03-30 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('headmaster', '0001_initial'),
        ('students', '0003_alter_student_current_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='student',
            name='current_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='headmaster.classroom'),
        ),
        migrations.DeleteModel(
            name='Classroom',
        ),
    ]
